### ISSUE TITLE
请问这个能用来开发微服务吗？

### ISSUE THREAD

**Issue by JIeJaitt** [iszmxw/vercel-golang#3]
如题，请问大佬一个vercel可以部署起多个服务的项目嘛

**Comment by iszmxw** [comment]
可以的，就是要注意下免费版本的vercel中函数10秒限制,还有内存方面的开销

Memory Size：1024 MB
Maximum Execution Duration：10 seconds

<img width="1493" alt="image" src="https://github.com/iszmxw/vercel-golang/assets/31272102/b68bc4c3-7423-496f-88d6-f14240b9d46e">

**Comment by JIeJaitt** [comment]
@iszmxw 谢谢大佬，不过那我一个项目有两个服务，部署的话得在vercel创建两个项目，然后每次编排不同的目录吗？有没有办法直接部署在一个项目里面呢？或者说vercel有没有办法指定构建命令先go build 然后 go run 一个，再go build go run另外一个，类似dockerfile一样或者说其他makefile一样的功能呢

**Comment by iszmxw** [comment]
这个没有办法，只能分开部署

**Comment by JIeJaitt** [comment]
@iszmxw 大佬,这个仓库根目录下的main.go函数是没有用是吧?

**Comment by iszmxw** [comment]
> @iszmxw 大佬,这个仓库根目录下的main.go函数是没有用是吧?

有用的，如果你不打算部署在 vercel 那就从 main.go 编译和启动

**Comment by JIeJaitt** [comment]
大佬知道vercel部署得某个子目录的时候,如果我修改了其他目录的内容怎么跳过这个项目的部署吗?我现在多个服务在一个仓库里面,当我修改了一个服务的内容的时候,其他服务会一起触发vercel的部署,我已经在设置里面设置了[Skip deployments](https://vercel.com/docs/monorepos#skipping-unaffected-projects) when there are no changes to the root directory or its dependencies.功能了
![image](https://github.com/user-attachments/assets/5883163e-c52b-4298-9398-bf483d93e074)

**Comment by iszmxw** [comment]
> 大佬知道vercel部署得某个子目录的时候,如果我修改了其他目录的内容怎么跳过这个项目的部署吗?我现在多个服务在一个仓库里面,当我修改了一个服务的内容的时候,其他服务会一起触发vercel的部署,我已经在设置里面设置了[Skip deployments](https://vercel.com/docs/monorepos#skipping-unaffected-projects) when there are no changes to the root directory or its dependencies.功能了 ![image](https://private-user-images.githubusercontent.com/77219045/397637546-5883163e-c52b-4298-9398-bf483d93e074.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NzY0MzQsIm5iZiI6MTczNDY3NjEzNCwicGF0aCI6Ii83NzIxOTA0NS8zOTc2Mzc1NDYtNTg4MzE2M2UtYzUyYi00Mjk4LTkzOTgtYmY0ODNkOTNlMDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA2Mjg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYzhiM2UxODFlNjk2NzE4MjRhNTgzZjhkMzkzMjI5ZDgzYTA1MGYxMmM5NjUyZjg0YjQ4MjY0OWZlYzAxNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EeQHM021oC1gDhp_Cb3s7gSkBfytyp4U54DaEh3j8J0)

你可以创建多个仓库来解决，一个仓库对应一个 vercel 项目，或者一个仓库创建多个子模块，一个模块包含一个 vercel.json 配置，单独部署子模块对应的目录
