### ISSUE TITLE
云函数？后台应用？

### ISSUE THREAD

**Issue by the-yex** [iszmxw/vercel-golang#4]
vercel 不是只支持云函数，不支持后台应用吗？能解释一下吗？

**Comment by iszmxw** [comment]
云函数运行起来不也是一样实现了后台应用

**Comment by the-yex** [comment]
> 云函数运行起来不也是一样实现了后台应用

那效果肯定差远了，只能说云函数对于事件驱动和按需运行的任务很便捷，有些东西还是只能常驻服务来做

**Comment by iszmxw** [comment]
> > 云函数运行起来不也是一样实现了后台应用
> 
> 那效果肯定差远了，只能说云函数对于事件驱动和按需运行的任务很便捷，有些东西还是只能常驻服务来做

常驻的肯定不行，vervel 官方免费的只有 10 秒，像微信机器人是肯定不行的
