### ISSUE TITLE
预览链接 504

### ISSUE THREAD

**Issue by liu874396180** [iszmxw/vercel-golang#5]
This Serverless Function has timed out.

Your connection is working correctly.

Vercel is working correctly.

504: GATEWAY_TIMEOUT
Code: FUNCTION_INVOCATION_TIMEOUT
ID: sin1::67j77-1723183176875-f628975378ac

If you are a visitor, contact the website owner or try again later.
If you are the owner, learn how to fix the error and check the logs.

**Comment by iszmxw** [comment]
> This Serverless Function has timed out.
> 
> Your connection is working correctly.
> 
> Vercel is working correctly.
> 
> 504: GATEWAY_TIMEOUT Code: FUNCTION_INVOCATION_TIMEOUT ID: sin1::67j77-1723183176875-f628975378ac
> 
> If you are a visitor, contact the website owner or try again later. If you are the owner, learn how to fix the error and check the logs.

数据库的配置改了，可以浏览了
